# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f891261b3ab09e30c9b67047433a9bfc00fe188c33876b9af0ef149b5f2b9633c3835893a2fcf52e4d8d05892fdcc7b4e18229f6e76c71ea12ff9d97667607e8
  api_key: 1ab57a02a9e7850f586640a2982d28c9

test:
  secret_key_base: 7019ccca2b347b208e6dc564fe060ad15402becef351b9c4411209f799beb0afede5d2396a682fa03f5fbfa22498efeb8dad530d51010c22630ec0476f3eff59
  api_key: 1ab57a02a9e7850f586640a2982d28c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_key: 1ab57a02a9e7850f586640a2982d28c9

